version: "3"
services:
  web:
    image: sentinull/friendly-hello:part2
    deploy:
      replicas: 12
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
